# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 60

image:
  repository: kaushikrahul08/go-app
  tag: greenyellow
  pullPolicy: IfNotPresent

service:
  name: go-app
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 30m
    memory: 30Mi


