# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  repository: aksregistrytgs.azurecr.io/goapp_v2
  tag: v2
  pullPolicy: Always

service:
  name: go-app
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 10Mi


